name:                sae
version:             0.3

description:         Please see the README on GitHub at <https://github.com/DoctorRyner/sae>

dependencies:
- base >= 4.7 && < 5
- generic-lens
- yaml
- bytestring

ghc-options:
- -Wall
- -Werror=incomplete-patterns

default-extensions:
- OverloadedStrings
- LambdaCase
- DeriveGeneric
- DuplicateRecordFields
- OverloadedLabels
- OverloadedStrings
- LambdaCase
- DataKinds
- TypeOperators

library:
  source-dirs: src

executables:
  sae-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Werror
    dependencies:
    - sae
