name:                sae
version:             0.1

dependencies:
- base >= 4.7 && < 5
- yaml
- either
- bytestring
- containers
- text
- unordered-containers
- process

executables:
  solve:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
