name:                sae
version:             0.1

dependencies:
- base >= 4.7 && < 5
- yaml
- bytestring
- text
- unordered-containers
- process
- async
- regex-compat
- regex-pcre
- vector

executables:
  sae:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
